export const PAGINATION_DEFAULT_LIMIT = 10;
export const PAGINATION_MAX_LIMIT = 100;
export const PAGINATION_MIN_LIMIT = 1;

export const PAGINATION_DEFAULT_PAGE_NUMBER = 1;
export const PAGINATION_MIN_PAGE_NUMBER = 1;
